version: '3.8'
services:
  dev-db:
    image: postgres:13.2
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_api_development
    networks:
      - my_api
networks:
  my_api:
